"""Claude-powered media prompt generation.

Instead of naive template concatenation, uses Claude to generate
specialized, optimized prompts for each media type - video (Veo),
image/thumbnail/story/carousel (Nano Banana 2), and post overlays.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from pydantic import BaseModel, Field

from supercooked.config import CLAUDE_MODEL, get_anthropic_client
from supercooked.identity.manager import get_voice_md, load_identity

logger = logging.getLogger(__name__)


class MediaPrompts(BaseModel):
    """Structured prompts for each media type, generated by Claude."""

    video_prompt: str = ""
    image_prompts: list[str] = Field(default_factory=list)
    thumbnail_prompt: str = ""
    story_prompt: str = ""
    carousel_prompts: list[str] = Field(default_factory=list)
    post_prompt: str = ""


_SYSTEM_PROMPT = """\
You are a media prompt engineer. Given a content idea, script, and creator persona,
generate specialized prompts optimized for each AI media generation model.

## Model-Specific Guidance

**Video (Veo 3.1):**
- Write cinematic scene descriptions with camera movement, lighting, mood
- Describe continuous visual narrative, NOT static shots
- The video will be extended to 15-20 seconds, so plan a visual arc
- Include pacing direction (fast cuts, slow pan, etc.)
- Mention scene transitions and visual flow
- Keep under 300 words

**Image (Nano Banana 2):**
- Detailed style descriptors: lighting, color palette, composition, mood
- Include art style direction (photorealistic, illustration, etc.)
- Nano Banana 2 excels at text rendering, physics-accurate lighting, and character consistency
- Describe the scene, not text to render
- Each prompt should be self-contained (don't reference other prompts)

**Thumbnail (Nano Banana 2):**
- Eye-catching, high contrast, vibrant
- Describe a creative visual concept that represents the content
- NOT just "person with title" - think about visual metaphors, dramatic compositions
- Should make someone want to click

**Story (Nano Banana 2, vertical 9:16):**
- Vertical composition, center-weighted
- Dramatic lighting, mood-driven
- Leave space at top and bottom for text overlays
- Atmospheric and immersive

**Post (Nano Banana 2):**
- Clean background that works with text overlay
- Mood and color should match the content tone
- Avoid busy scenes that would make overlaid text unreadable

**Carousel (Nano Banana 2):**
- Each slide should be visually cohesive (same style, color palette)
- Each slide illustrates a different point/section
- Think of it as a visual story across slides

## Response Format

Return ONLY valid JSON with this exact structure:
{
  "video_prompt": "...",
  "image_prompts": ["prompt for visual cue 1", "prompt for visual cue 2", ...],
  "thumbnail_prompt": "...",
  "story_prompt": "...",
  "carousel_prompts": ["slide 1 prompt", "slide 2 prompt", ...],
  "post_prompt": "..."
}

Generate prompts ONLY for the requested content types. Leave others as empty string/list.
"""


async def generate_media_prompts(
    slug: str,
    idea: Any,
    script_data: dict[str, Any],
    content_types: list[str],
) -> MediaPrompts:
    """Generate optimized media prompts using Claude.

    Parameters
    ----------
    slug:
        Identity slug - used to load persona and face config.
    idea:
        ContentIdea with title, concept, template, tags.
    script_data:
        Script data dict with hook, script, visual_cues, etc.
    content_types:
        List of content types to generate prompts for.

    Returns
    -------
    MediaPrompts with per-type optimized prompts.
    """
    identity = load_identity(slug)
    persona = identity.persona
    voice_md = get_voice_md(slug)

    # Load face config for character description
    face_description = ""
    try:
        from supercooked.identity.schemas import FaceConfig

        import yaml
        from supercooked.config import IDENTITIES_DIR
        face_config_path = IDENTITIES_DIR / slug / "face" / "config.yaml"
        if face_config_path.exists():
            with open(face_config_path) as f:
                face_data = yaml.safe_load(f) or {}
            face = FaceConfig(**face_data)
            if face.base_prompt:
                face_description = f"\n\nCharacter appearance: {face.base_prompt}"
                if face.style:
                    face_description += f"\nArt style: {face.style}"
                if face.negative_prompt:
                    face_description += f"\nAvoid in visuals: {face.negative_prompt}"
    except Exception:
        pass  # Face config is optional

    visual_cues = script_data.get("visual_cues", [])
    hook = script_data.get("hook", "")
    script = script_data.get("script", idea.concept)
    duration = script_data.get("duration_estimate_seconds", 30)

    user_prompt = f"""Content idea:
- Title: {idea.title}
- Concept: {idea.concept}
- Template/Format: {idea.template}
- Tags: {', '.join(idea.tags)}
- Duration: {duration}s

Script hook: "{hook}"
Script: "{script}"
Visual cues: {json.dumps(visual_cues)}

Creator persona:
- Archetype: {persona.archetype}
- Tone: {persona.tone}
{face_description}

Content types to generate prompts for: {', '.join(content_types)}

Generate optimized media prompts for each requested content type."""

    client = get_anthropic_client()

    try:
        response = await client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=3000,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )

        raw = response.content[0].text.strip()
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            start = raw.find("{")
            end = raw.rfind("}") + 1
            if start == -1 or end == 0:
                logger.error("Claude returned non-JSON media prompts: %s", raw[:500])
                return _fallback_prompts(idea, script_data, content_types)
            data = json.loads(raw[start:end])

        return MediaPrompts(**data)

    except Exception as exc:
        logger.error("Media prompt generation failed: %s", exc)
        return _fallback_prompts(idea, script_data, content_types)


def _fallback_prompts(
    idea: Any,
    script_data: dict[str, Any],
    content_types: list[str],
) -> MediaPrompts:
    """Build basic fallback prompts when Claude is unavailable."""
    visual_cues = script_data.get("visual_cues", [])
    hook = script_data.get("hook", "")
    script = script_data.get("script", idea.concept)
    visual = visual_cues[0] if visual_cues else idea.concept

    prompts = MediaPrompts()

    if "video" in content_types:
        prompts.video_prompt = (
            f"A cinematic short-form video about: {idea.title}. "
            f"{script}. Visual style: modern, dynamic, engaging."
        )
    if "image" in content_types:
        prompts.image_prompts = list(visual_cues) or [visual]
    if "thumbnail" in content_types:
        prompts.thumbnail_prompt = (
            f"Eye-catching thumbnail concept for: {idea.title}. "
            f"Vibrant, high contrast, dramatic composition."
        )
    if "story" in content_types:
        prompts.story_prompt = (
            f"Dramatic vertical image for: {idea.title}. "
            f"{visual}. Atmospheric, immersive, center-weighted composition."
        )
    if "carousel" in content_types:
        prompts.carousel_prompts = list(visual_cues) or [visual]
    if "post" in content_types:
        prompts.post_prompt = (
            f"Clean background image for text overlay about: {idea.title}. "
            f"{visual}. Mood-driven, not too busy."
        )

    return prompts
